### ISSUE TITLE
Organizar pastas para salvar imagens de usuário e de pet

### ISSUE THREAD

**Issue by LeonardoAragaoDev** [adotapetorg/adotapetorg-back-end#1]
No servidor adicionar pasta **imagens/user** e **imagens/pet**, para deixar ainda mais organizadas as imagens

**Comment by Lewoaragao** [comment]
### ✔️ Versão publicada

> 📆 **Data:** 20/05/2023  
> 🕙 **Hora:** 00:03 
> 👤  **Autor:** @Lewoaragao

**Comment by LeonardoAragaoDev** [comment]
### ✔️ Versão publicada

> 📆 **Data:** 20/05/2023  
> 🕙 **Hora:** 00:03 
> 👤  **Autor:** @Lewoaragao
